/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.106
 * Generated at: 2025-07-03 09:41:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>PahanaEdu Dashboard</title>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            background: linear-gradient(120deg, #e0eafc 0%, #cfdef3 100%);\r\n");
      out.write("            font-family: 'Roboto', Arial, sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("        .navbar {\r\n");
      out.write("            background: #2193b0;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            padding: 1rem 2rem;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            box-shadow: 0 2px 8px rgba(33,147,176,0.08);\r\n");
      out.write("        }\r\n");
      out.write("        .navbar .logo {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            font-size: 1.3rem;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            letter-spacing: 1px;\r\n");
      out.write("        }\r\n");
      out.write("        .navbar .logo i {\r\n");
      out.write("            margin-right: 0.7rem;\r\n");
      out.write("            font-size: 1.7rem;\r\n");
      out.write("        }\r\n");
      out.write("        .navbar .user {\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 0.5rem;\r\n");
      out.write("        }\r\n");
      out.write("        .navbar .user i {\r\n");
      out.write("            font-size: 1.2rem;\r\n");
      out.write("        }\r\n");
      out.write("        .dashboard-container {\r\n");
      out.write("            max-width: 700px;\r\n");
      out.write("            margin: 2.5rem auto 0 auto;\r\n");
      out.write("            background: #fff;\r\n");
      out.write("            border-radius: 14px;\r\n");
      out.write("            box-shadow: 0 4px 24px 0 rgba(31, 38, 135, 0.10);\r\n");
      out.write("            padding: 2.5rem 2rem;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        .dashboard-title {\r\n");
      out.write("            font-size: 2rem;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            color: #2193b0;\r\n");
      out.write("            margin-bottom: 1.2rem;\r\n");
      out.write("        }\r\n");
      out.write("        .dashboard-welcome {\r\n");
      out.write("            font-size: 1.15rem;\r\n");
      out.write("            color: #444;\r\n");
      out.write("            margin-bottom: 2rem;\r\n");
      out.write("        }\r\n");
      out.write("        .dashboard-actions {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-wrap: wrap;\r\n");
      out.write("            gap: 1.2rem;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("        }\r\n");
      out.write("        .dashboard-action {\r\n");
      out.write("            background: linear-gradient(90deg, #2193b0, #6dd5ed);\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("            padding: 1.1rem 2.2rem;\r\n");
      out.write("            font-size: 1.1rem;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            box-shadow: 0 2px 8px rgba(33,147,176,0.09);\r\n");
      out.write("            transition: background 0.2s, transform 0.1s;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 0.7rem;\r\n");
      out.write("        }\r\n");
      out.write("        .dashboard-action:hover {\r\n");
      out.write("            background: linear-gradient(90deg, #6dd5ed, #2193b0);\r\n");
      out.write("            transform: translateY(-2px) scale(1.03);\r\n");
      out.write("        }\r\n");
      out.write("        @media (max-width: 600px) {\r\n");
      out.write("            .dashboard-container {\r\n");
      out.write("                padding: 1.2rem 0.5rem;\r\n");
      out.write("            }\r\n");
      out.write("            .dashboard-title {\r\n");
      out.write("                font-size: 1.3rem;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"navbar\">\r\n");
      out.write("        <div class=\"logo\"><i class=\"fa fa-book-open\"></i> PahanaEdu</div>\r\n");
      out.write("        <div class=\"user\">\r\n");
      out.write("            <i class=\"fa fa-user-circle\"></i>\r\n");
      out.write("            ");
 
                com.pahanaedu.model.User user = (com.pahanaedu.model.User) session.getAttribute("user");
                if (user != null) {
                    out.print(user.getUsername());
                } else {
                    out.print("Guest");
                }
            
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"dashboard-container\">\r\n");
      out.write("        <div class=\"dashboard-title\">Welcome to Your Dashboard</div>\r\n");
      out.write("        <div class=\"dashboard-welcome\">\r\n");
      out.write("            Hello, <b>");
 if (user != null) { out.print(user.getUsername()); } else { out.print("Guest"); } 
      out.write("</b>!<br>\r\n");
      out.write("            This is your main dashboard. You can add your main features and navigation here.\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"dashboard-actions\">\r\n");
      out.write("            <button class=\"dashboard-action\"><i class=\"fa fa-user\"></i> Profile</button>\r\n");
      out.write("            <button class=\"dashboard-action\"><i class=\"fa fa-cog\"></i> Settings</button>\r\n");
      out.write("            <button class=\"dashboard-action\"><i class=\"fa fa-sign-out-alt\"></i> Logout</button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html> ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
