/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.106
 * Generated at: 2025-07-17 10:48:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Dashboard - Pahana Edu Bookshop</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <style>\r\n");
      out.write("        :root {\r\n");
      out.write("            --sidebar-bg: #1e293b;\r\n");
      out.write("            --sidebar-text: #ffffff;\r\n");
      out.write("            --main-bg: #f1f5f9;\r\n");
      out.write("            --primary-btn: #3b82f6;\r\n");
      out.write("            --primary-btn-hover: #60a5fa;\r\n");
      out.write("            --sidebar-width: 250px;\r\n");
      out.write("        }\r\n");
      out.write("        body {\r\n");
      out.write("            background: var(--main-bg);\r\n");
      out.write("        }\r\n");
      out.write("        .sidebar {\r\n");
      out.write("            position: fixed;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            height: 100vh;\r\n");
      out.write("            width: var(--sidebar-width);\r\n");
      out.write("            background: var(--sidebar-bg);\r\n");
      out.write("            color: var(--sidebar-text);\r\n");
      out.write("            z-index: 1000;\r\n");
      out.write("            box-shadow: 2px 0 10px rgba(0,0,0,0.07);\r\n");
      out.write("        }\r\n");
      out.write("        .sidebar-header {\r\n");
      out.write("            padding: 24px 10px 16px 10px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            border-bottom: 1px solid rgba(255,255,255,0.08);\r\n");
      out.write("        }\r\n");
      out.write("        .sidebar-header h5 {\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            letter-spacing: 1px;\r\n");
      out.write("            color: var(--sidebar-text);\r\n");
      out.write("        }\r\n");
      out.write("        .sidebar-header small {\r\n");
      out.write("            color: #cbd5e1;\r\n");
      out.write("        }\r\n");
      out.write("        .sidebar-menu {\r\n");
      out.write("            padding: 24px 0;\r\n");
      out.write("        }\r\n");
      out.write("        .sidebar-menu .nav-link {\r\n");
      out.write("            color: var(--sidebar-text);\r\n");
      out.write("            padding: 14px 28px;\r\n");
      out.write("            font-size: 1.08rem;\r\n");
      out.write("            border-radius: 30px 0 0 30px;\r\n");
      out.write("            margin-bottom: 6px;\r\n");
      out.write("            transition: all 0.2s;\r\n");
      out.write("            opacity: 0.85;\r\n");
      out.write("        }\r\n");
      out.write("        .sidebar-menu .nav-link i {\r\n");
      out.write("            color: var(--sidebar-text);\r\n");
      out.write("            margin-right: 8px;\r\n");
      out.write("        }\r\n");
      out.write("        .sidebar-menu .nav-link:hover,\r\n");
      out.write("        .sidebar-menu .nav-link.active {\r\n");
      out.write("            color: var(--sidebar-text);\r\n");
      out.write("            background: var(--primary-btn-hover);\r\n");
      out.write("            opacity: 1;\r\n");
      out.write("        }\r\n");
      out.write("        .sidebar-menu .nav-link:hover i,\r\n");
      out.write("        .sidebar-menu .nav-link.active i {\r\n");
      out.write("            color: var(--sidebar-text);\r\n");
      out.write("        }\r\n");
      out.write("        .main-content {\r\n");
      out.write("            margin-left: var(--sidebar-width);\r\n");
      out.write("            padding: 32px 24px 24px 24px;\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            background: var(--main-bg);\r\n");
      out.write("        }\r\n");
      out.write("        .stats-card {\r\n");
      out.write("            background: white;\r\n");
      out.write("            border-radius: 16px;\r\n");
      out.write("            padding: 24px 18px;\r\n");
      out.write("            box-shadow: 0 4px 18px rgba(0,0,0,0.08);\r\n");
      out.write("            transition: transform 0.2s;\r\n");
      out.write("            border: none;\r\n");
      out.write("        }\r\n");
      out.write("        .stats-card:hover {\r\n");
      out.write("            transform: translateY(-6px) scale(1.03);\r\n");
      out.write("        }\r\n");
      out.write("        .stats-icon {\r\n");
      out.write("            width: 56px;\r\n");
      out.write("            height: 56px;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            font-size: 26px;\r\n");
      out.write("            color: white;\r\n");
      out.write("            margin-bottom: 14px;\r\n");
      out.write("            box-shadow: 0 2px 8px rgba(0,0,0,0.08);\r\n");
      out.write("        }\r\n");
      out.write("        .stats-customers { background: linear-gradient(135deg, #3b82f6 0%, #60a5fa 100%); }\r\n");
      out.write("        .stats-items { background: linear-gradient(135deg, #fbbf24 0%, #fde68a 100%); color: #1e293b; }\r\n");
      out.write("        .stats-sales { background: linear-gradient(135deg, #10b981 0%, #6ee7b7 100%); }\r\n");
      out.write("        .stats-revenue { background: linear-gradient(135deg, #a78bfa 0%, #fbc2eb 100%); }\r\n");
      out.write("        .card-header {\r\n");
      out.write("            background: var(--primary-btn);\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            border-radius: 12px 12px 0 0;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("        }\r\n");
      out.write("        .btn-primary {\r\n");
      out.write("            background: var(--primary-btn);\r\n");
      out.write("            border: none;\r\n");
      out.write("        }\r\n");
      out.write("        .btn-primary:hover, .btn-primary:focus {\r\n");
      out.write("            background: var(--primary-btn-hover);\r\n");
      out.write("        }\r\n");
      out.write("        .btn-success {\r\n");
      out.write("            background: linear-gradient(90deg, #10b981 0%, #6ee7b7 100%);\r\n");
      out.write("            border: none;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("        }\r\n");
      out.write("        .btn-success:hover, .btn-success:focus {\r\n");
      out.write("            background: #059669;\r\n");
      out.write("        }\r\n");
      out.write("        .btn-info {\r\n");
      out.write("            background: linear-gradient(90deg, #a78bfa 0%, #fbc2eb 100%);\r\n");
      out.write("            border: none;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("        }\r\n");
      out.write("        .btn-info:hover, .btn-info:focus {\r\n");
      out.write("            background: #7c3aed;\r\n");
      out.write("        }\r\n");
      out.write("        .btn-outline-danger {\r\n");
      out.write("            border-color: #f3574b;\r\n");
      out.write("            color: #f3574b;\r\n");
      out.write("        }\r\n");
      out.write("        .btn-outline-danger:hover {\r\n");
      out.write("            background: #f3574b;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("        }\r\n");
      out.write("        .list-group-item {\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-bottom: 1px solid #f1f1f1;\r\n");
      out.write("        }\r\n");
      out.write("        .list-group-item:last-child {\r\n");
      out.write("            border-bottom: none;\r\n");
      out.write("        }\r\n");
      out.write("        @media (max-width: 991.98px) {\r\n");
      out.write("            .main-content {\r\n");
      out.write("                margin-left: 0;\r\n");
      out.write("                padding: 16px 6px;\r\n");
      out.write("            }\r\n");
      out.write("            .sidebar {\r\n");
      out.write("                width: 100vw;\r\n");
      out.write("                height: auto;\r\n");
      out.write("                position: relative;\r\n");
      out.write("                box-shadow: none;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Sidebar -->\r\n");
      out.write("    <div class=\"sidebar\">\r\n");
      out.write("        <div class=\"sidebar-header\">\r\n");
      out.write("            <i class=\"fas fa-book-reader fa-2x mb-2\"></i>\r\n");
      out.write("            <h5>Pahana Edu</h5>\r\n");
      out.write("            <small>Bookshop Management</small>\r\n");
      out.write("        </div>\r\n");
      out.write("        <nav class=\"sidebar-menu\">\r\n");
      out.write("            <ul class=\"nav flex-column\">\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link active\" href=\"dashboard.jsp\">\r\n");
      out.write("                        <i class=\"fas fa-tachometer-alt\"></i> Dashboard\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/customer/list\">\r\n");
      out.write("                        <i class=\"fas fa-users\"></i> Customers\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/item/list\">\r\n");
      out.write("                        <i class=\"fas fa-box\"></i> Items\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/billing/create\">\r\n");
      out.write("                        <i class=\"fas fa-receipt\"></i> Create Bill\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/billing/list\">\r\n");
      out.write("                        <i class=\"fas fa-list\"></i> Bills\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/report/sales\">\r\n");
      out.write("                        <i class=\"fas fa-chart-bar\"></i> Reports\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.print(request.getContextPath());
      out.write("/help.jsp\">\r\n");
      out.write("                        <i class=\"fas fa-question-circle\"></i> Help\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Main Content -->\r\n");
      out.write("    <div class=\"main-content\">\r\n");
      out.write("        <div class=\"d-flex justify-content-between align-items-center mb-4\">\r\n");
      out.write("            <h2 class=\"fw-bold\" style=\"letter-spacing:1px;\">Dashboard</h2>\r\n");
      out.write("            <a href=\"logout\" class=\"btn btn-outline-danger\">\r\n");
      out.write("                <i class=\"fas fa-sign-out-alt\"></i> Logout\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Statistics Cards -->\r\n");
      out.write("        <div class=\"row mb-4\">\r\n");
      out.write("            <div class=\"col-md-3 mb-3\">\r\n");
      out.write("                <div class=\"stats-card text-center\">\r\n");
      out.write("                    <div class=\"stats-icon stats-customers mx-auto\">\r\n");
      out.write("                        <i class=\"fas fa-users\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h3 class=\"fw-bold\">150</h3>\r\n");
      out.write("                    <p class=\"text-muted mb-0\">Total Customers</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-3 mb-3\">\r\n");
      out.write("                <div class=\"stats-card text-center\">\r\n");
      out.write("                    <div class=\"stats-icon stats-items mx-auto\">\r\n");
      out.write("                        <i class=\"fas fa-box\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h3 class=\"fw-bold\">75</h3>\r\n");
      out.write("                    <p class=\"text-muted mb-0\">Total Items</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-3 mb-3\">\r\n");
      out.write("                <div class=\"stats-card text-center\">\r\n");
      out.write("                    <div class=\"stats-icon stats-sales mx-auto\">\r\n");
      out.write("                        <i class=\"fas fa-receipt\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h3 class=\"fw-bold\">45</h3>\r\n");
      out.write("                    <p class=\"text-muted mb-0\">Total Bills</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-3 mb-3\">\r\n");
      out.write("                <div class=\"stats-card text-center\">\r\n");
      out.write("                    <div class=\"stats-icon stats-revenue mx-auto\">\r\n");
      out.write("                        <i class=\"fas fa-dollar-sign\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h3 class=\"fw-bold\">Rs. 125,000</h3>\r\n");
      out.write("                    <p class=\"text-muted mb-0\">Total Revenue</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Quick Actions & Recent Activity -->\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-6 mb-3\">\r\n");
      out.write("                <div class=\"card h-100\">\r\n");
      out.write("                    <div class=\"card-header\">\r\n");
      out.write("                        <h5 class=\"mb-0\"><i class=\"fas fa-bolt\"></i> Quick Actions</h5>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <div class=\"d-grid gap-2\">\r\n");
      out.write("                            <a href=\"customer/add.jsp\" class=\"btn btn-primary\">\r\n");
      out.write("                                <i class=\"fas fa-user-plus\"></i> Add Customer\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <a href=\"item/add.jsp\" class=\"btn btn-success\">\r\n");
      out.write("                                <i class=\"fas fa-plus\"></i> Add Item\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <a href=\"billing/create\" class=\"btn btn-info\">\r\n");
      out.write("                                <i class=\"fas fa-receipt\"></i> Create Bill\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-6 mb-3\">\r\n");
      out.write("                <div class=\"card h-100\">\r\n");
      out.write("                    <div class=\"card-header\">\r\n");
      out.write("                        <h5 class=\"mb-0\"><i class=\"fas fa-clock\"></i> Recent Activity</h5>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        <div class=\"list-group list-group-flush\">\r\n");
      out.write("                            <div class=\"list-group-item\">\r\n");
      out.write("                                <div class=\"d-flex justify-content-between\">\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                        <strong>New customer registered</strong>\r\n");
      out.write("                                        <p class=\"text-muted mb-0\">John Doe - Account #1001</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <small class=\"text-muted\">2 hours ago</small>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"list-group-item\">\r\n");
      out.write("                                <div class=\"d-flex justify-content-between\">\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                        <strong>Bill generated</strong>\r\n");
      out.write("                                        <p class=\"text-muted mb-0\">Bill #2024-001 - Rs. 1,250</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <small class=\"text-muted\">4 hours ago</small>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"list-group-item\">\r\n");
      out.write("                                <div class=\"d-flex justify-content-between\">\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                        <strong>Item added</strong>\r\n");
      out.write("                                        <p class=\"text-muted mb-0\">\"A/L Physics\" Book - Stock: 20</p>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <small class=\"text-muted\">6 hours ago</small>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html> ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
