/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.106
 * Generated at: 2025-07-02 16:26:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <title>PahanaEdu Login</title>\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css\">\n");
      out.write("    <style>\n");
      out.write("        body {\n");
      out.write("            min-height: 100vh;\n");
      out.write("            margin: 0;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            background: linear-gradient(120deg, #e0eafc 0%, #cfdef3 100%);\n");
      out.write("            font-family: 'Roboto', Arial, sans-serif;\n");
      out.write("            position: relative;\n");
      out.write("        }\n");
      out.write("        body::before {\n");
      out.write("            content: '';\n");
      out.write("            position: absolute;\n");
      out.write("            top: 0; left: 0; right: 0; bottom: 0;\n");
      out.write("            background: url('https://www.toptal.com/designers/subtlepatterns/patterns/symphony.png');\n");
      out.write("            opacity: 0.13;\n");
      out.write("            z-index: 0;\n");
      out.write("        }\n");
      out.write("        .login-container {\n");
      out.write("            position: relative;\n");
      out.write("            z-index: 1;\n");
      out.write("            background: #fff;\n");
      out.write("            padding: 2.5rem 2rem 2rem 2rem;\n");
      out.write("            border-radius: 18px;\n");
      out.write("            box-shadow: 0 8px 32px 0 rgba(31, 38, 135, 0.18), 0 1.5px 6px 0 rgba(0,0,0,0.07);\n");
      out.write("            min-width: 340px;\n");
      out.write("            max-width: 370px;\n");
      out.write("            width: 100%;\n");
      out.write("            text-align: center;\n");
      out.write("            transition: box-shadow 0.2s;\n");
      out.write("        }\n");
      out.write("        .login-container:hover {\n");
      out.write("            box-shadow: 0 12px 40px 0 rgba(31, 38, 135, 0.22), 0 2px 8px 0 rgba(0,0,0,0.09);\n");
      out.write("        }\n");
      out.write("        .login-logo {\n");
      out.write("            width: 70px;\n");
      out.write("            height: 70px;\n");
      out.write("            background: linear-gradient(135deg, #2193b0 60%, #6dd5ed 100%);\n");
      out.write("            border-radius: 50%;\n");
      out.write("            margin: 0 auto 1.1rem auto;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            box-shadow: 0 2px 8px rgba(33,147,176,0.13);\n");
      out.write("        }\n");
      out.write("        .login-logo i {\n");
      out.write("            color: #fff;\n");
      out.write("            font-size: 2.2rem;\n");
      out.write("        }\n");
      out.write("        .login-logo span {\n");
      out.write("            color: #fff;\n");
      out.write("            font-size: 2.1rem;\n");
      out.write("            font-weight: 700;\n");
      out.write("            letter-spacing: 1px;\n");
      out.write("            font-family: 'Roboto', Arial, sans-serif;\n");
      out.write("        }\n");
      out.write("        .login-title {\n");
      out.write("            font-size: 1.6rem;\n");
      out.write("            font-weight: 700;\n");
      out.write("            color: #2193b0;\n");
      out.write("            margin-bottom: 1.2rem;\n");
      out.write("            letter-spacing: 0.5px;\n");
      out.write("        }\n");
      out.write("        .login-form {\n");
      out.write("            position: relative;\n");
      out.write("        }\n");
      out.write("        .input-group {\n");
      out.write("            position: relative;\n");
      out.write("            margin-bottom: 1.1rem;\n");
      out.write("        }\n");
      out.write("        .input-group i {\n");
      out.write("            position: absolute;\n");
      out.write("            left: 13px;\n");
      out.write("            top: 50%;\n");
      out.write("            transform: translateY(-50%);\n");
      out.write("            color: #bdbdbd;\n");
      out.write("            font-size: 1.1rem;\n");
      out.write("        }\n");
      out.write("        .input-group .toggle-password {\n");
      out.write("            position: absolute;\n");
      out.write("            right: 22px;\n");
      out.write("            top: 50%;\n");
      out.write("            transform: translateY(-50%);\n");
      out.write("            background: none;\n");
      out.write("            border: none;\n");
      out.write("            color: #bdbdbd;\n");
      out.write("            font-size: 1.1rem;\n");
      out.write("            cursor: pointer;\n");
      out.write("            padding: 0;\n");
      out.write("            z-index: 2;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            height: 100%;\n");
      out.write("        }\n");
      out.write("        .input-group input {\n");
      out.write("            width: 85%;\n");
      out.write("            max-width: 260px;\n");
      out.write("            margin: 0 auto;\n");
      out.write("            padding-right: 2.2rem;\n");
      out.write("            padding: 0.5rem 0.5rem 0.5rem 2.0rem;\n");
      out.write("            border: 1.5px solid #e3e3e3;\n");
      out.write("            border-radius: 7px;\n");
      out.write("            font-size: 0.95rem;\n");
      out.write("            background: #f7fafd;\n");
      out.write("            transition: border 0.2s, box-shadow 0.2s;\n");
      out.write("        }\n");
      out.write("        .input-group input:focus {\n");
      out.write("            border: 1.5px solid #2193b0;\n");
      out.write("            outline: none;\n");
      out.write("            box-shadow: 0 0 0 2px #6dd5ed33;\n");
      out.write("        }\n");
      out.write("        .password-tooltip {\n");
      out.write("            position: absolute;\n");
      out.write("            right: 38px;\n");
      out.write("            top: 50%;\n");
      out.write("            transform: translateY(-50%);\n");
      out.write("            color: #2193b0;\n");
      out.write("            font-size: 1.1rem;\n");
      out.write("            cursor: pointer;\n");
      out.write("        }\n");
      out.write("        .tooltip-text {\n");
      out.write("            visibility: hidden;\n");
      out.write("            width: 180px;\n");
      out.write("            background-color: #2193b0;\n");
      out.write("            color: #fff;\n");
      out.write("            text-align: left;\n");
      out.write("            border-radius: 6px;\n");
      out.write("            padding: 0.5rem;\n");
      out.write("            position: absolute;\n");
      out.write("            z-index: 2;\n");
      out.write("            right: 110%;\n");
      out.write("            top: 50%;\n");
      out.write("            transform: translateY(-50%);\n");
      out.write("            font-size: 0.95rem;\n");
      out.write("            opacity: 0;\n");
      out.write("            transition: opacity 0.2s;\n");
      out.write("        }\n");
      out.write("        .password-tooltip:hover .tooltip-text {\n");
      out.write("            visibility: visible;\n");
      out.write("            opacity: 1;\n");
      out.write("        }\n");
      out.write("        .remember-forgot {\n");
      out.write("            display: flex;\n");
      out.write("            justify-content: space-between;\n");
      out.write("            align-items: center;\n");
      out.write("            margin-bottom: 1.1rem;\n");
      out.write("        }\n");
      out.write("        .remember-forgot label {\n");
      out.write("            font-size: 0.98rem;\n");
      out.write("            color: #555;\n");
      out.write("            font-weight: 400;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            gap: 0.3rem;\n");
      out.write("        }\n");
      out.write("        .remember-forgot a {\n");
      out.write("            color: #2193b0;\n");
      out.write("            text-decoration: none;\n");
      out.write("            font-size: 0.98rem;\n");
      out.write("            transition: text-decoration 0.2s;\n");
      out.write("        }\n");
      out.write("        .remember-forgot a:hover {\n");
      out.write("            text-decoration: underline;\n");
      out.write("        }\n");
      out.write("        .login-form button[type=\"submit\"] {\n");
      out.write("            width: 100%;\n");
      out.write("            padding: 0.85rem;\n");
      out.write("            background: linear-gradient(90deg, #2193b0, #6dd5ed);\n");
      out.write("            color: #fff;\n");
      out.write("            border: none;\n");
      out.write("            border-radius: 7px;\n");
      out.write("            font-size: 1.13rem;\n");
      out.write("            font-weight: 700;\n");
      out.write("            cursor: pointer;\n");
      out.write("            box-shadow: 0 2px 8px rgba(33,147,176,0.09);\n");
      out.write("            transition: background 0.2s, transform 0.1s;\n");
      out.write("            position: relative;\n");
      out.write("        }\n");
      out.write("        .login-form button[type=\"submit\"]:hover {\n");
      out.write("            background: linear-gradient(90deg, #6dd5ed, #2193b0);\n");
      out.write("            transform: translateY(-2px) scale(1.03);\n");
      out.write("        }\n");
      out.write("        .spinner {\n");
      out.write("            display: none;\n");
      out.write("            position: absolute;\n");
      out.write("            right: 18px;\n");
      out.write("            top: 50%;\n");
      out.write("            transform: translateY(-50%);\n");
      out.write("            width: 22px;\n");
      out.write("            height: 22px;\n");
      out.write("            border: 3px solid #fff;\n");
      out.write("            border-top: 3px solid #2193b0;\n");
      out.write("            border-radius: 50%;\n");
      out.write("            animation: spin 1s linear infinite;\n");
      out.write("        }\n");
      out.write("        @keyframes spin {\n");
      out.write("            0% { transform: translateY(-50%) rotate(0deg); }\n");
      out.write("            100% { transform: translateY(-50%) rotate(360deg); }\n");
      out.write("        }\n");
      out.write("        .signup-link {\n");
      out.write("            margin-top: 1.2rem;\n");
      out.write("            font-size: 1rem;\n");
      out.write("            color: #555;\n");
      out.write("        }\n");
      out.write("        .signup-link a {\n");
      out.write("            color: #2193b0;\n");
      out.write("            text-decoration: none;\n");
      out.write("            font-weight: 500;\n");
      out.write("            margin-left: 0.3rem;\n");
      out.write("        }\n");
      out.write("        .signup-link a:hover {\n");
      out.write("            text-decoration: underline;\n");
      out.write("        }\n");
      out.write("        .error-message {\n");
      out.write("            color: #e74c3c;\n");
      out.write("            margin-top: 1rem;\n");
      out.write("            font-size: 1rem;\n");
      out.write("            background: #ffeaea;\n");
      out.write("            border-radius: 5px;\n");
      out.write("            padding: 0.6rem 0.8rem;\n");
      out.write("        }\n");
      out.write("        @media (max-width: 480px) {\n");
      out.write("            .login-container {\n");
      out.write("                min-width: 90vw;\n");
      out.write("                padding: 1.5rem 0.5rem 1.2rem 0.5rem;\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"login-container\" aria-label=\"Login form\">\n");
      out.write("        <div class=\"login-logo\" aria-hidden=\"true\"><i class=\"fa fa-book-open\"></i></div>\n");
      out.write("        <div class=\"login-title\">PahanaEdu Login</div>\n");
      out.write("        <form class=\"login-form\" method=\"post\" action=\"login\" autocomplete=\"on\" aria-label=\"Login form\" onsubmit=\"return showSpinner()\">\n");
      out.write("            <div class=\"input-group\">\n");
      out.write("                <i class=\"fa fa-user\" aria-hidden=\"true\"></i>\n");
      out.write("                <label for=\"username\" class=\"sr-only\">Username</label>\n");
      out.write("                <input type=\"text\" id=\"username\" name=\"username\" required autofocus autocomplete=\"username\" aria-label=\"Username\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"input-group\">\n");
      out.write("                <i class=\"fa fa-lock\" aria-hidden=\"true\"></i>\n");
      out.write("                <label for=\"password\" class=\"sr-only\">Password</label>\n");
      out.write("                <input type=\"password\" id=\"password\" name=\"password\" required autocomplete=\"current-password\" aria-label=\"Password\">\n");
      out.write("                <button type=\"button\" class=\"toggle-password\" tabindex=\"0\" aria-label=\"Show or hide password\" onclick=\"togglePassword()\">\n");
      out.write("                    <i class=\"fa fa-eye\" id=\"togglePasswordIcon\"></i>\n");
      out.write("                </button>\n");
      out.write("               \n");
      out.write("            </div>\n");
      out.write("            <div class=\"remember-forgot\">\n");
      out.write("                <label><input type=\"checkbox\" name=\"remember\" tabindex=\"0\"> Remember me</label>\n");
      out.write("                <a href=\"#\" tabindex=\"0\">Forgot password?</a>\n");
      out.write("            </div>\n");
      out.write("            <button type=\"submit\" aria-label=\"Login\">\n");
      out.write("                Login\n");
      out.write("                <span class=\"spinner\" id=\"spinner\"></span>\n");
      out.write("            </button>\n");
      out.write("        </form>\n");
      out.write("        ");
 if (request.getAttribute("error") != null) { 
      out.write("\n");
      out.write("            <div class=\"error-message\">");
      out.print( request.getAttribute("error") );
      out.write("</div>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("        <div class=\"signup-link\">\n");
      out.write("            New to PahanaEdu?\n");
      out.write("            <a href=\"#\" tabindex=\"0\">Sign up</a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <style>\n");
      out.write("        .sr-only { position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); border: 0; }\n");
      out.write("    </style>\n");
      out.write("    <script>\n");
      out.write("        function togglePassword() {\n");
      out.write("            const pwd = document.getElementById('password');\n");
      out.write("            const icon = document.getElementById('togglePasswordIcon');\n");
      out.write("            if (pwd.type === 'password') {\n");
      out.write("                pwd.type = 'text';\n");
      out.write("                icon.classList.remove('fa-eye');\n");
      out.write("                icon.classList.add('fa-eye-slash');\n");
      out.write("            } else {\n");
      out.write("                pwd.type = 'password';\n");
      out.write("                icon.classList.remove('fa-eye-slash');\n");
      out.write("                icon.classList.add('fa-eye');\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("        function showSpinner() {\n");
      out.write("            document.getElementById('spinner').style.display = 'inline-block';\n");
      out.write("            return true;\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
